-- V15 - ADICAO DE COLUNAS DA BASE DL

ALTER TABLE tb_chamado 
ADD COLUMN IF NOT EXISTS sla_data_limite TIMESTAMP,
ADD COLUMN IF NOT EXISTS material_descricao VARCHAR(255),
ADD COLUMN IF NOT EXISTS comercial VARCHAR(255),
ADD COLUMN IF NOT EXISTS cliente_nome VARCHAR(255),
ADD COLUMN IF NOT EXISTS texto_abertura TEXT,
ADD COLUMN IF NOT EXISTS texto_encerrado TEXT,
ADD COLUMN IF NOT EXISTS ocorrencia_chamado VARCHAR(255),
ADD COLUMN IF NOT EXISTS reincidente VARCHAR(50),
ADD COLUMN IF NOT EXISTS defeito VARCHAR(255),
ADD COLUMN IF NOT EXISTS sla_cef VARCHAR(255);
